### PR TITLE
Add localization

### PR DESCRIPTION
**Pull request by a2937**
My main goal was to add localization to this application. I also tried to fix some small things up where I could.

### CODE REVIEW

**Comment by SneakyTactician** [comment]
This PR looks really good!
I appreciate the fine comb through my code, and the tiny little style fixes.

**Comment by SneakyTactician** [comment]
One thing: Can you change the name of the resx file to something better, such as "strings", "language", "lang", or "text". Something that reminds developers that the resx file holds strings needed for localization. The name "API" confuses me as to what the resource file contains. It only describes the file's location.

**Comment by a2937** [comment]
Sure thing. I would be more than happy to change the name.

**Comment by SneakyTactician** [comment]
Thanks for the PR!

**Pull request merged**
